---
title: Information update on BC soil database  
output: html_notebook
---
<br></br>
Jin Zhang 
Last edited: Jan 20, 2021 
<br></br>

#### <em> Pre: </em> Loading packes and set up the working directory


```{r}
packages4thisscript <- c("anytime","tidyr", "dplyr", "sp", "rgdal", "ggplot2", "stringr")
lapply(packages4thisscript, library, character.only = TRUE)
```

```{r}
setwd("/Volumes/WorkDISC/BCSOIL_tables/Update_BCSOILTables") # need to set up the workDirectory accordingly 
dir("_data")
dir("_data/_archive")
dir("_data/_updates")
```
#### 1) Update the site information table  
 - Archive the latest site table to archieve folder with a time stamp. 
 - Read in current latest site table (Completed by last update)
 - Read in filled site update template 

```{r}

dir("_data")
dir("_data/_archive")
dir("_data/_updates")
file.rename("_data/BCSIS_site.csv", paste("_data/_archive/bcsis_site_", Sys.time(), ".csv", sep = ""))
s_current <- read.csv("Volumes/WorkDISC/BCSOIL_tables/Update_BCSOILTables/_data/BCSIS_site.csv", stringsAsFactors = FALSE)
s_newdata <- read.csv("_data/_updates/BC_site_update_template.csv", stringsAsFactors = FALSE)

```

### - The End - 

